//! Room layouts: the wall network generated by the rooms of one plane.
//!
//! A layout owns the arrangement of its rooms and generates ONE wall
//! network from it, so a boundary shared by two rooms is one wall and T
//! and X junctions are exact.
//!
//! **Effective regions.** Rooms are ranked by precedence (higher first;
//! ties by entity id). A room's effective region is its boundary minus
//! the union of the boundaries of the rooms ranked above it, so effective
//! regions never overlap. A region can be empty or in several pieces
//! ([`RegionStatus`]).
//!
//! **Wall graph.** The edges of all effective regions, split at every
//! vertex that lies on them and deduplicated: a segment shared by two
//! regions is one wall. Each segment knows the original room edges that
//! cover it (collinear overlap). A segment is hidden (no wall) when ANY
//! covering room edge is hidden.
//!
//! **Footprint.** Walls are centered on the visible segments,
//! `thickness_m` wide: one rectangle per segment, ending square at both
//! nodes, plus at every node with two or more walls a kite that fills
//! each outside corner (a gap between consecutive walls wider than a
//! half turn) up to the miter point of the two wall faces, or a bevel
//! when the miter would reach farther than [`MITER_LIMIT`] half
//! thicknesses. Inside corners, T and X junctions need no filler: the
//! rectangles meet exactly. A wall end at a node with no other wall is
//! square. The union of all pieces is the footprint.
//!
//! **Openings** are anchored to a room edge: `offset_m` along it from its
//! start to the opening's left edge. An opening must lie in one
//! [`opening_span`] of its edge: the part of the edge covered by visible
//! wall, clear of the other walls at its junctions. A through opening
//! cuts the whole thickness; a niche is `depth_m` deep from the face on
//! the room's side (the left of the room edge, its interior). An opening
//! that does not fit is left out and reported ([`LayoutIssue`]).
//!
//! **Height layers.** The wall rises from the plane to the top reference
//! H (as for wall runs). Heights 0, H, and every opening's bottom and
//! top split it into layers; each layer is the footprint minus the
//! openings active in it, as prisms.

use serde::{Deserialize, Serialize};

use crate::document::Document;
use crate::entity::{Params, slot};
use crate::id::EntityId;
use crate::room::{RoomData, RoomError};
use crate::sketch::geom::{self, P2};
use crate::sketch::layers::{OverlayRule, boolean};
use crate::subref::{ProvenancePath, RoomWallPart};
use crate::wall_run::{DOOR_BELOW_BASE_M, OpeningKind};

pub use crate::wall::DEFAULT_PARTITION_THICKNESS_M;

pub mod ops;

/// Largest miter length at an outside corner, in half thicknesses from
/// the node; sharper outside corners are beveled.
pub const MITER_LIMIT: f64 = 4.0;

/// Distance (meters) under which two plan points are the same point.
const TOL: f64 = 1e-6;

/// A rectangular opening in the wall of one room edge.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct RoomOpening {
    pub id: u32,
    /// The room whose edge carries the opening (a room of the layout).
    pub room: EntityId,
    /// The edge: its start point id in the room's boundary.
    pub edge: u32,
    /// Along the edge from its start to the opening's left edge.
    pub offset_m: f64,
    /// Height of the bottom above the plane (windows; ignored for doors).
    pub sill_m: f64,
    pub width_m: f64,
    pub height_m: f64,
    pub kind: OpeningKind,
    /// `None` goes through the wall; `Some(d)` is a niche `d` deep from
    /// the face on the room's side.
    pub depth_m: Option<f64>,
}

/// The data of a room layout, mirroring `Params::RoomLayout`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RoomLayoutData {
    pub thickness_m: f64,
    pub height_m: f64,
    pub top_offset_m: f64,
    pub openings: Vec<RoomOpening>,
}

impl RoomLayoutData {
    /// The layout data of `Params::RoomLayout`.
    pub fn from_params(params: &Params) -> Option<RoomLayoutData> {
        match params {
            Params::RoomLayout {
                thickness_m,
                height_m,
                top_offset_m,
                openings,
            } => Some(RoomLayoutData {
                thickness_m: *thickness_m,
                height_m: *height_m,
                top_offset_m: *top_offset_m,
                openings: openings.clone(),
            }),
            _ => None,
        }
    }

    /// `Params::RoomLayout` with this data.
    pub fn into_params(self) -> Params {
        Params::RoomLayout {
            thickness_m: self.thickness_m,
            height_m: self.height_m,
            top_offset_m: self.top_offset_m,
            openings: self.openings,
        }
    }

    /// The next free opening id (largest + 1).
    pub fn next_opening_id(&self) -> u32 {
        self.openings.iter().map(|o| o.id).max().map_or(0, |m| m.saturating_add(1))
    }
}

/// A layout with the data of its rooms, in rooms-slot order: what the
/// pure functions of this module work on.
#[derive(Debug, Clone, PartialEq)]
pub struct LayoutInput {
    pub layout: RoomLayoutData,
    pub rooms: Vec<(EntityId, RoomData)>,
}

impl LayoutInput {
    /// The data of room `id`.
    pub fn room(&self, id: EntityId) -> Option<&RoomData> {
        self.rooms.iter().find(|(r, _)| *r == id).map(|(_, data)| data)
    }
}

/// The input of layout `layout` from the document.
pub fn inputs(doc: &Document, layout: EntityId) -> Option<LayoutInput> {
    let record = doc.entity(layout)?;
    let data = RoomLayoutData::from_params(&record.params)?;
    let ids: Vec<EntityId> = record
        .inputs
        .get(slot::ROOM_LAYOUT_ROOMS)
        .map(|s| s.referenced().collect())
        .unwrap_or_default();
    let rooms = ids
        .into_iter()
        .filter_map(|id| Some((id, RoomData::from_params(&doc.entity(id)?.params)?)))
        .collect();
    Some(LayoutInput { layout: data, rooms })
}

/// The top reference height of a layout above its plane (meters), from
/// params only, computed exactly as evaluation does.
pub fn layout_top_height(doc: &Document, layout: EntityId) -> Option<f64> {
    let record = doc.entity(layout)?;
    let data = RoomLayoutData::from_params(&record.params)?;
    let plane = |index: usize| record.inputs.get(index).and_then(|s| s.referenced().next());
    match plane(slot::ROOM_LAYOUT_TOP) {
        None => Some(data.height_m),
        Some(top) => {
            let base = crate::workplane::plane_elevation(doc, plane(slot::ROOM_LAYOUT_PLANE)?)?;
            let top = crate::workplane::plane_elevation(doc, top)?;
            Some((top - base) + data.top_offset_m)
        }
    }
}

/// Typed failure of a layout check or operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LayoutError {
    /// A size, height, or offset is NaN or infinite.
    NonFinite,
    /// The thickness is not positive.
    InvalidThickness,
    /// The fixed height is not positive.
    InvalidHeight,
    /// Two openings share this id.
    DuplicateOpeningId(u32),
    /// No opening has this id.
    UnknownOpening(u32),
    /// This opening's size, sill, or depth is invalid.
    InvalidOpening(u32),
    /// This opening's room is not a room of the layout.
    UnknownRoom(u32),
    /// This opening does not fit its edge's wall span.
    OpeningDoesNotFit(u32),
    /// A room is invalid.
    Room { room: EntityId, error: RoomError },
    /// The top reference is at or below the plane.
    TopBelowBase,
    /// A 2D boolean failed.
    Boolean,
    /// This room is not a room of the layout.
    RoomNotInLayout(EntityId),
}

impl std::fmt::Display for LayoutError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LayoutError::NonFinite => write!(f, "a size or height is not finite"),
            LayoutError::InvalidThickness => write!(f, "the wall thickness must be positive"),
            LayoutError::InvalidHeight => write!(f, "the wall height must be positive"),
            LayoutError::DuplicateOpeningId(id) => write!(f, "opening id {id} is used twice"),
            LayoutError::UnknownOpening(id) => write!(f, "no opening {id}"),
            LayoutError::InvalidOpening(id) => write!(
                f,
                "opening {id} needs a positive width and height and a sill at or above the base"
            ),
            LayoutError::UnknownRoom(id) => write!(f, "opening {id} is on a room outside the layout"),
            LayoutError::OpeningDoesNotFit(id) => write!(f, "opening {id} does not fit its wall"),
            LayoutError::Room { room, error } => write!(f, "room {}: {error}", room.0),
            LayoutError::TopBelowBase => write!(f, "the wall top is at or below its base"),
            LayoutError::Boolean => write!(f, "a polygon boolean failed"),
            LayoutError::RoomNotInLayout(id) => write!(f, "room {} is not in the layout", id.0),
        }
    }
}

impl std::error::Error for LayoutError {}

fn finite(values: &[f64]) -> Result<(), LayoutError> {
    if values.iter().all(|v| v.is_finite()) {
        Ok(())
    } else {
        Err(LayoutError::NonFinite)
    }
}

/// One opening's own values: positive size, a sill at or above the base
/// for windows, a positive depth for niches.
fn check_opening(opening: &RoomOpening) -> Result<(), LayoutError> {
    finite(&[opening.offset_m, opening.sill_m, opening.width_m, opening.height_m])?;
    let sill_ok = opening.kind == OpeningKind::Door || opening.sill_m >= 0.0;
    let depth_ok = opening.depth_m.is_none_or(|d| d.is_finite() && d > 0.0);
    if opening.width_m <= TOL || opening.height_m <= TOL || !sill_ok || !depth_ok {
        return Err(LayoutError::InvalidOpening(opening.id));
    }
    Ok(())
}

/// Structural validity, as the layout commands require it: finite
/// values, a positive thickness and height, unique opening ids, valid
/// opening sizes, and openings on rooms of the layout. An opening on an
/// edge its room no longer has does not fit (a room edit can remove the
/// edge); that is an evaluation issue, not a structural error.
pub fn validate_structure(input: &LayoutInput) -> Result<(), LayoutError> {
    let data = &input.layout;
    finite(&[data.thickness_m, data.height_m, data.top_offset_m])?;
    if data.thickness_m <= TOL {
        return Err(LayoutError::InvalidThickness);
    }
    if data.height_m <= 0.0 {
        return Err(LayoutError::InvalidHeight);
    }
    let mut ids = std::collections::BTreeSet::new();
    for opening in &data.openings {
        if !ids.insert(opening.id) {
            return Err(LayoutError::DuplicateOpeningId(opening.id));
        }
        check_opening(opening)?;
        input.room(opening.room).ok_or(LayoutError::UnknownRoom(opening.id))?;
    }
    Ok(())
}

/// Full validity: structure, every room valid, every opening in a span
/// of its edge.
pub fn validate(input: &LayoutInput) -> Result<(), LayoutError> {
    validate_structure(input)?;
    for (id, room) in &input.rooms {
        crate::room::validate(room).map_err(|error| LayoutError::Room { room: *id, error })?;
    }
    let arrangement = arrange(input)?;
    for opening in &input.layout.openings {
        if !arrangement.fits(opening) {
            return Err(LayoutError::OpeningDoesNotFit(opening.id));
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------
// Regions.
// ---------------------------------------------------------------------

/// How a room came out of the arrangement.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RegionStatus {
    /// One piece.
    Whole,
    /// Cut into this many pieces by higher rooms.
    Pieces(usize),
    /// Entirely covered by higher rooms.
    Empty,
    /// The room is invalid and takes no part in the layout.
    Invalid(RoomError),
}

/// A room's effective region in plan (the layout plane's (u, v)).
#[derive(Debug, Clone, PartialEq)]
pub struct RoomRegion {
    pub room: EntityId,
    /// Polygons: an outer ring (counter-clockwise) and hole rings
    /// (clockwise) each.
    pub polygons: Vec<Vec<Vec<P2>>>,
    pub area_m2: f64,
    pub status: RegionStatus,
}

/// A problem that leaves part of a layout out while the rest evaluates.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LayoutIssue {
    /// This room is invalid and generates nothing.
    RoomInvalid { room: EntityId, error: RoomError },
    /// This opening is not on an edge of a valid room of the layout, or
    /// does not fit its edge's wall span; it is left out.
    OpeningDoesNotFit { opening: u32 },
}

impl std::fmt::Display for LayoutIssue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LayoutIssue::RoomInvalid { room, error } => write!(f, "room {}: {error}", room.0),
            LayoutIssue::OpeningDoesNotFit { opening } => {
                write!(f, "opening {opening} does not fit its wall")
            }
        }
    }
}

// ---------------------------------------------------------------------
// Arrangement: regions and the wall graph.
// ---------------------------------------------------------------------

/// A room edge that covers a wall segment.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Cover {
    pub room: EntityId,
    pub edge: u32,
    /// The room edge runs the same way as the segment (`a -> b`); the
    /// room interior is then on the segment's left.
    pub same_direction: bool,
    pub hidden: bool,
}

/// One segment of the wall graph.
#[derive(Debug, Clone, PartialEq)]
pub struct WallSegment {
    pub a: P2,
    pub b: P2,
    /// Covering room edges, in room rank order.
    pub covers: Vec<Cover>,
    pub hidden: bool,
}

/// Points snapped to shared positions on a grid.
struct Grid {
    cells: std::collections::HashMap<(i64, i64), Vec<usize>>,
    points: Vec<P2>,
}

impl Grid {
    fn new() -> Grid {
        Grid { cells: std::collections::HashMap::new(), points: Vec::new() }
    }

    fn cell(p: P2) -> (i64, i64) {
        ((p[0] / TOL).floor() as i64, (p[1] / TOL).floor() as i64)
    }

    fn find(&self, p: P2) -> Option<usize> {
        let (x, y) = Self::cell(p);
        let mut best: Option<(f64, usize)> = None;
        for dx in -1..=1 {
            for dy in -1..=1 {
                for i in self.cells.get(&(x + dx, y + dy)).into_iter().flatten() {
                    if let Some(q) = self.points.get(*i) {
                        let d = geom::dist(*q, p);
                        if d <= TOL && best.is_none_or(|(bd, _)| d < bd) {
                            best = Some((d, *i));
                        }
                    }
                }
            }
        }
        best.map(|(_, i)| i)
    }

    fn insert(&mut self, p: P2) -> usize {
        if let Some(i) = self.find(p) {
            return i;
        }
        let i = self.points.len();
        self.cells.entry(Self::cell(p)).or_default().push(i);
        self.points.push(p);
        i
    }

    fn point(&self, i: usize) -> P2 {
        self.points.get(i).copied().unwrap_or([0.0, 0.0])
    }
}

/// The arrangement of a layout's rooms.
pub struct Arrangement {
    pub regions: Vec<RoomRegion>,
    pub segments: Vec<WallSegment>,
    pub issues: Vec<LayoutIssue>,
    /// Node indices of every segment's ends.
    ends: Vec<(usize, usize)>,
    nodes: Grid,
    /// Valid rooms in rank order.
    ranked: Vec<(EntityId, RoomData)>,
    half: f64,
}

fn unit(a: P2, b: P2) -> Option<P2> {
    let l = geom::dist(a, b);
    (l > TOL).then(|| geom::scale(geom::sub(b, a), 1.0 / l))
}

fn left(d: P2) -> P2 {
    [-d[1], d[0]]
}

fn shape_area(shape: &[Vec<P2>]) -> f64 {
    shape.iter().map(|ring| geom::signed_area(ring)).sum()
}

/// The arrangement of `input`'s rooms: regions, the wall graph, and the
/// issues of invalid rooms.
pub fn arrange(input: &LayoutInput) -> Result<Arrangement, LayoutError> {
    let mut regions = Vec::with_capacity(input.rooms.len());
    let mut issues = Vec::new();
    let mut ranked: Vec<(EntityId, RoomData)> = Vec::new();
    for (id, room) in &input.rooms {
        match crate::room::validate(room) {
            Ok(()) => ranked.push((*id, room.clone())),
            Err(error) => {
                issues.push(LayoutIssue::RoomInvalid { room: *id, error });
                regions.push(RoomRegion {
                    room: *id,
                    polygons: vec![],
                    area_m2: 0.0,
                    status: RegionStatus::Invalid(error),
                });
            }
        }
    }
    ranked.sort_by(|(ia, a), (ib, b)| b.precedence.cmp(&a.precedence).then(ia.cmp(ib)));

    // Effective regions.
    let mut higher: Vec<Vec<P2>> = Vec::new();
    let mut shapes_of: Vec<(EntityId, Vec<Vec<Vec<P2>>>)> = Vec::with_capacity(ranked.len());
    for (id, room) in &ranked {
        let polygon = room.polygon();
        let shapes = boolean(std::slice::from_ref(&polygon), &higher, OverlayRule::Difference)
            .map_err(|_| LayoutError::Boolean)?;
        let shapes: Vec<Vec<Vec<P2>>> =
            shapes.into_iter().filter(|s| shape_area(s) > TOL * TOL).collect();
        let area: f64 = shapes.iter().map(|s| shape_area(s)).sum();
        let status = match shapes.len() {
            0 => RegionStatus::Empty,
            1 => RegionStatus::Whole,
            n => RegionStatus::Pieces(n),
        };
        regions.push(RoomRegion { room: *id, polygons: shapes.clone(), area_m2: area, status });
        shapes_of.push((*id, shapes));
        higher.push(polygon);
    }
    // Regions in rooms-slot order.
    regions.sort_by_key(|r| input.rooms.iter().position(|(id, _)| *id == r.room));

    // Wall graph: region edges, split at every vertex on them, deduplicated.
    let mut nodes = Grid::new();
    let mut raw: Vec<(usize, usize)> = Vec::new();
    for (_, shapes) in &shapes_of {
        for ring in shapes.iter().flatten() {
            let n = ring.len();
            for i in 0..n {
                let (Some(p), Some(q)) = (ring.get(i), ring.get((i + 1) % n)) else { continue };
                let (a, b) = (nodes.insert(*p), nodes.insert(*q));
                if a != b {
                    raw.push((a, b));
                }
            }
        }
    }
    let mut pairs: std::collections::BTreeSet<(usize, usize)> = std::collections::BTreeSet::new();
    for (a, b) in raw {
        let (pa, pb) = (nodes.point(a), nodes.point(b));
        let len = geom::dist(pa, pb);
        let mut inner: Vec<(f64, usize)> = (0..nodes.points.len())
            .filter(|k| *k != a && *k != b)
            .filter_map(|k| {
                let p = nodes.point(k);
                let t = geom::dot(geom::sub(p, pa), geom::sub(pb, pa)) / (len * len);
                (t * len > TOL && (1.0 - t) * len > TOL && geom::point_segment_distance(p, pa, pb) <= TOL)
                    .then_some((t, k))
            })
            .collect();
        inner.sort_by(|x, y| x.0.total_cmp(&y.0));
        let chain: Vec<usize> =
            std::iter::once(a).chain(inner.into_iter().map(|(_, k)| k)).chain(std::iter::once(b)).collect();
        for w in chain.windows(2) {
            if let [x, y] = w
                && x != y
            {
                pairs.insert((*x.min(y), *x.max(y)));
            }
        }
    }

    let mut segments = Vec::with_capacity(pairs.len());
    let mut ends = Vec::with_capacity(pairs.len());
    for (a, b) in pairs {
        let (pa, pb) = (nodes.point(a), nodes.point(b));
        let mut covers = Vec::new();
        for (id, room) in &ranked {
            for edge in room.edges() {
                let Some((ea, eb)) = room.edge_ends(edge) else { continue };
                if geom::point_segment_distance(pa, ea, eb) <= TOL
                    && geom::point_segment_distance(pb, ea, eb) <= TOL
                {
                    covers.push(Cover {
                        room: *id,
                        edge,
                        same_direction: geom::dot(geom::sub(pb, pa), geom::sub(eb, ea)) > 0.0,
                        hidden: room.is_hidden(edge),
                    });
                }
            }
        }
        let hidden = covers.iter().any(|c| c.hidden);
        segments.push(WallSegment { a: pa, b: pb, covers, hidden });
        ends.push((a, b));
    }

    Ok(Arrangement {
        regions,
        segments,
        issues,
        ends,
        nodes,
        ranked,
        half: input.layout.thickness_m / 2.0,
    })
}

impl Arrangement {
    /// Unit directions of the visible walls leaving node `node`, with
    /// their segment index.
    fn arms(&self, node: usize) -> Vec<(P2, usize)> {
        let p = self.nodes.point(node);
        let mut arms: Vec<(P2, usize)> = self
            .segments
            .iter()
            .zip(self.ends.iter())
            .enumerate()
            .filter(|(_, (s, _))| !s.hidden)
            .filter_map(|(i, (_, (a, b)))| {
                let other = if *a == node {
                    *b
                } else if *b == node {
                    *a
                } else {
                    return None;
                };
                Some((unit(p, self.nodes.point(other))?, i))
            })
            .collect();
        arms.sort_by(|(x, _), (y, _)| x[1].atan2(x[0]).total_cmp(&y[1].atan2(y[0])));
        arms
    }

    /// The plan footprint: centered wall rectangles plus outside-corner
    /// kites, as boolean rings (not yet united).
    fn footprint_pieces(&self) -> Vec<Vec<P2>> {
        let h = self.half;
        let mut pieces = Vec::new();
        for segment in self.segments.iter().filter(|s| !s.hidden) {
            let Some(d) = unit(segment.a, segment.b) else { continue };
            let n = geom::scale(left(d), h);
            pieces.push(vec![
                geom::sub(segment.a, n),
                geom::sub(segment.b, n),
                geom::add(segment.b, n),
                geom::add(segment.a, n),
            ]);
        }
        for node in 0..self.nodes.points.len() {
            let arms = self.arms(node);
            if arms.len() < 2 {
                continue;
            }
            let p = self.nodes.point(node);
            let k = arms.len();
            for i in 0..k {
                let (Some((di, _)), Some((dj, _))) = (arms.get(i), arms.get((i + 1) % k)) else { continue };
                let (ai, aj) = (di[1].atan2(di[0]), dj[1].atan2(dj[0]));
                let mut gap = aj - ai;
                if gap <= 0.0 {
                    gap += std::f64::consts::TAU;
                }
                if gap <= std::f64::consts::PI + 1e-9 {
                    continue; // inside corner, straight run, T or X: covered
                }
                let li = geom::add(p, geom::scale(left(*di), h));
                let rj = geom::sub(p, geom::scale(left(*dj), h));
                let miter = h / (gap / 2.0).sin().abs();
                if miter <= MITER_LIMIT * h {
                    let bisector = ai + gap / 2.0;
                    let m = geom::add(p, [miter * bisector.cos(), miter * bisector.sin()]);
                    pieces.push(vec![p, li, m, rj]);
                } else {
                    pieces.push(vec![p, li, rj]);
                }
            }
        }
        pieces
    }

    /// The united plan footprint.
    pub fn footprint(&self) -> Result<Vec<Vec<Vec<P2>>>, LayoutError> {
        boolean(&self.footprint_pieces(), &[], OverlayRule::Union).map_err(|_| LayoutError::Boolean)
    }

    /// How far along a wall leaving node `node` in direction `d` the
    /// other walls at the node reach.
    fn clearance(&self, node: Option<usize>, d: P2) -> f64 {
        let Some(node) = node else { return 0.0 };
        let h = self.half;
        self.arms(node)
            .iter()
            .filter_map(|(e, _)| {
                let sin = geom::cross(d, *e).abs();
                let cos = geom::dot(d, *e);
                (sin > 1e-9).then(|| h * (1.0 + cos.abs()) / sin)
            })
            .fold(0.0, f64::max)
    }

    /// The spans of room edge `edge` of room `room` where an opening can
    /// go: `(min, max)` along the edge from its start, where visible wall
    /// covers the edge, clear of the other walls at its junctions.
    pub fn spans(&self, room: EntityId, edge: u32) -> Vec<(f64, f64)> {
        let Some(data) = self.ranked.iter().find(|(id, _)| *id == room).map(|(_, d)| d) else {
            return vec![];
        };
        let Some((ea, eb)) = data.edge_ends(edge) else { return vec![] };
        let Some(d) = unit(ea, eb) else { return vec![] };
        let s_of = |p: P2| geom::dot(geom::sub(p, ea), d);
        let mut pieces: Vec<(f64, f64)> = self
            .segments
            .iter()
            .filter(|s| !s.hidden)
            .filter(|s| {
                geom::point_segment_distance(s.a, ea, eb) <= TOL
                    && geom::point_segment_distance(s.b, ea, eb) <= TOL
            })
            .map(|s| {
                let (x, y) = (s_of(s.a), s_of(s.b));
                (x.min(y), x.max(y))
            })
            .collect();
        pieces.sort_by(|x, y| x.0.total_cmp(&y.0));
        let node_at = |s: f64| self.nodes.find(geom::add(ea, geom::scale(d, s)));
        let back = geom::scale(d, -1.0);
        let junction = |s: f64| self.clearance(node_at(s), d) > 0.0;
        // Merge touching pieces unless another wall meets there.
        let mut runs: Vec<(f64, f64)> = Vec::new();
        for (lo, hi) in pieces {
            match runs.last_mut() {
                Some(last) if (lo - last.1).abs() <= TOL && !junction(lo) => last.1 = hi,
                _ => runs.push((lo, hi)),
            }
        }
        runs.into_iter()
            .map(|(lo, hi)| (lo + self.clearance(node_at(lo), d), hi - self.clearance(node_at(hi), back)))
            .filter(|(lo, hi)| hi - lo > TOL)
            .collect()
    }

    /// True when `opening` lies in a span of its edge.
    pub fn fits(&self, opening: &RoomOpening) -> bool {
        check_opening(opening).is_ok()
            && self
                .spans(opening.room, opening.edge)
                .iter()
                .any(|(lo, hi)| opening.offset_m >= lo - TOL && opening.offset_m + opening.width_m <= hi + TOL)
    }
}

/// The spans of a room edge where an opening can go (see
/// [`Arrangement::spans`]).
pub fn opening_span(input: &LayoutInput, room: EntityId, edge: u32) -> Result<Vec<(f64, f64)>, LayoutError> {
    Ok(arrange(input)?.spans(room, edge))
}

// ---------------------------------------------------------------------
// Evaluation plan.
// ---------------------------------------------------------------------

/// One height layer: plan shapes (outer ring then holes) with a name per
/// ring edge.
#[derive(Debug, Clone)]
pub(crate) struct LayerPlan {
    pub z0: f64,
    pub z1: f64,
    pub shapes: Vec<Vec<Vec<P2>>>,
    pub names: Vec<Vec<Vec<Option<ProvenancePath>>>>,
}

/// Everything evaluation needs.
pub(crate) struct LayoutPlan {
    pub regions: Vec<RoomRegion>,
    pub issues: Vec<LayoutIssue>,
    pub layers: Vec<LayerPlan>,
}

/// A fitted opening in plan and height.
struct PlacedOpening {
    opening: RoomOpening,
    /// Plan rectangle (counter-clockwise).
    rect: Vec<P2>,
    /// Index of the rectangle edge that is a niche back.
    back: Option<usize>,
    z0: f64,
    z1: f64,
}

fn place(arr: &Arrangement, opening: &RoomOpening) -> Option<PlacedOpening> {
    let room = arr.ranked.iter().find(|(id, _)| *id == opening.room).map(|(_, d)| d)?;
    let (ea, eb) = room.edge_ends(opening.edge)?;
    let d = unit(ea, eb)?;
    let n = left(d);
    let h = arr.half;
    let margin = h.max(0.01);
    let (inner, back) = match opening.depth_m {
        Some(depth) if depth < 2.0 * h - TOL => (h - depth, true),
        _ => (-h - margin, false),
    };
    let outer = h + margin;
    let (s0, s1) = (opening.offset_m, opening.offset_m + opening.width_m);
    let at = |s: f64, w: f64| geom::add(ea, geom::add(geom::scale(d, s), geom::scale(n, w)));
    // Counter-clockwise: (s0, inner), (s1, inner), (s1, outer), (s0, outer).
    let rect = vec![at(s0, inner), at(s1, inner), at(s1, outer), at(s0, outer)];
    let (z0, z1) = match opening.kind {
        OpeningKind::Door => (-DOOR_BELOW_BASE_M, opening.height_m),
        OpeningKind::Window => (opening.sill_m, opening.sill_m + opening.height_m),
    };
    Some(PlacedOpening { opening: *opening, rect, back: back.then_some(0), z0, z1 })
}

/// Plans the layers of a layout with top reference `height`.
pub(crate) fn plan(input: &LayoutInput, height: f64) -> Result<LayoutPlan, LayoutError> {
    validate_structure(input)?;
    if !(height.is_finite() && height > TOL) {
        return Err(LayoutError::TopBelowBase);
    }
    let arr = arrange(input)?;
    let mut issues = arr.issues.clone();
    let mut placed = Vec::new();
    for opening in &input.layout.openings {
        match arr.fits(opening).then(|| place(&arr, opening)).flatten() {
            Some(p) => placed.push(p),
            None => issues.push(LayoutIssue::OpeningDoesNotFit { opening: opening.id }),
        }
    }
    let footprint = arr.footprint()?;
    let footprint_rings: Vec<Vec<P2>> = footprint.iter().flatten().cloned().collect();

    let mut cuts: Vec<f64> = vec![0.0, height];
    for p in &placed {
        cuts.push(p.z0.clamp(0.0, height));
        cuts.push(p.z1.clamp(0.0, height));
    }
    cuts.sort_by(f64::total_cmp);
    cuts.dedup_by(|b, a| (*b - *a).abs() <= TOL);

    let rank = |room: EntityId| arr.ranked.iter().position(|(id, _)| *id == room).unwrap_or(usize::MAX);
    let mut layers = Vec::new();
    for w in cuts.windows(2) {
        let [z0, z1] = w else { continue };
        if z1 - z0 <= TOL {
            continue;
        }
        let mid = (z0 + z1) / 2.0;
        let active: Vec<&PlacedOpening> = placed.iter().filter(|p| p.z0 < mid && mid < p.z1).collect();
        let rects: Vec<Vec<P2>> = active.iter().map(|p| p.rect.clone()).collect();
        let shapes = boolean(&footprint_rings, &rects, OverlayRule::Difference).map_err(|_| LayoutError::Boolean)?;
        let shapes: Vec<Vec<Vec<P2>>> = shapes.into_iter().filter(|s| shape_area(s).abs() > TOL * TOL).collect();
        let names = shapes
            .iter()
            .map(|shape| {
                shape
                    .iter()
                    .map(|ring| {
                        let n = ring.len();
                        (0..n)
                            .map(|i| {
                                let p = ring.get(i).copied().unwrap_or([0.0; 2]);
                                let q = ring.get((i + 1) % n).copied().unwrap_or(p);
                                name_edge(&arr, &active, &rank, p, q)
                            })
                            .collect()
                    })
                    .collect()
            })
            .collect();
        layers.push(LayerPlan { z0: *z0, z1: *z1, shapes, names });
    }
    Ok(LayoutPlan { regions: arr.regions, issues, layers })
}

/// The name of a plan edge of a layer: an opening reveal, a wall face
/// (named by the room it faces, or the outside of the first covering
/// room), or a wall end.
fn name_edge(
    arr: &Arrangement,
    active: &[&PlacedOpening],
    rank: &dyn Fn(EntityId) -> usize,
    p: P2,
    q: P2,
) -> Option<ProvenancePath> {
    let on = |a: P2, b: P2| geom::point_segment_distance(p, a, b) <= TOL && geom::point_segment_distance(q, a, b) <= TOL;
    for placed in active {
        let n = placed.rect.len();
        for i in 0..n {
            let (Some(a), Some(b)) = (placed.rect.get(i), placed.rect.get((i + 1) % n)) else { continue };
            if on(*a, *b) {
                let part = if placed.back == Some(i) {
                    RoomWallPart::NicheBack { opening: placed.opening.id }
                } else {
                    RoomWallPart::Opening { opening: placed.opening.id }
                };
                return Some(ProvenancePath::RoomWall {
                    room: placed.opening.room,
                    edge: placed.opening.edge,
                    part,
                });
            }
        }
    }
    let h = arr.half;
    let mid = geom::lerp(p, q, 0.5);
    let mut best: Option<(f64, usize, bool)> = None;
    for (i, segment) in arr.segments.iter().enumerate().filter(|(_, s)| !s.hidden) {
        let Some(d) = unit(segment.a, segment.b) else { continue };
        let n = left(d);
        let length = geom::dist(segment.a, segment.b);
        for side in [true, false] {
            let offset = if side { h } else { -h };
            let across = |x: P2| geom::dot(geom::sub(x, segment.a), n) - offset;
            if across(p).abs() > TOL || across(q).abs() > TOL {
                continue;
            }
            let s = geom::dot(geom::sub(mid, segment.a), d);
            let outside = if s < 0.0 { -s } else if s > length { s - length } else { 0.0 };
            if best.is_none_or(|(b, _, _)| outside < b) {
                best = Some((outside, i, side));
            }
        }
    }
    if let Some((_, i, left_side)) = best {
        let segment = arr.segments.get(i)?;
        let facing = segment
            .covers
            .iter()
            .filter(|c| c.same_direction == left_side)
            .min_by_key(|c| rank(c.room));
        if let Some(cover) = facing {
            return Some(ProvenancePath::RoomWall { room: cover.room, edge: cover.edge, part: RoomWallPart::Inside });
        }
        let first = segment.covers.iter().min_by_key(|c| rank(c.room))?;
        return Some(ProvenancePath::RoomWall { room: first.room, edge: first.edge, part: RoomWallPart::Outside });
    }
    // A wall end or a bevel: the nearest visible wall.
    let nearest = arr
        .segments
        .iter()
        .filter(|s| !s.hidden)
        .min_by(|x, y| {
            geom::point_segment_distance(mid, x.a, x.b).total_cmp(&geom::point_segment_distance(mid, y.a, y.b))
        })?;
    let first = nearest.covers.iter().min_by_key(|c| rank(c.room))?;
    Some(ProvenancePath::RoomWall { room: first.room, edge: first.edge, part: RoomWallPart::End })
}
