//! Selections — declarative targeting of entities and subelements
//! (docs/ARCHITECTURE.md §3.5).
//!
//! A `Selection` entity stores a predicate AST plus an explicit scope in
//! its params. This module is **structural only**: the AST is a closed,
//! serde-serializable data type with no evaluation semantics here.
//! Membership resolution (and the per-kind dirtying indexes that make
//! live selections cheap) belong to the evaluation layer.

use serde::{Deserialize, Serialize};

use crate::entity::EntityKind;
use crate::id::EntityId;

/// Closed predicate AST for selections. No user-provided code: every
/// predicate is total, panic-free, serializable, and expressible over the
/// C ABI. Geometric variants are placeholders for the evaluation layer —
/// they carry real parameters but are not interpreted by the substrate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum PredicateAst {
    /// Entity kind filter.
    KindIs(EntityKind),
    /// Geometric placeholder: both endpoints lie on the horizontal plane
    /// `z` (meters, Z-up — docs/ARCHITECTURE.md §7) within `tol`.
    EndpointsOnPlane { z: f64, tol: f64 },
    /// Geometric placeholder: curve length within `[min, max]` meters.
    LengthBetween { min: f64, max: f64 },
    /// Geometric placeholder: contained in the axis-aligned box.
    WithinBox { min: [f64; 3], max: [f64; 3] },
    /// Provenance test: the candidate is owned by (generated by) `owner`.
    OwnerIs(EntityId),
    And(Vec<PredicateAst>),
    Or(Vec<PredicateAst>),
    Not(Box<PredicateAst>),
}

/// Explicit selection scope (docs/ARCHITECTURE.md §3.5). Scoped selections
/// are preferred; `Global` is the one sanctioned, explicitly-opted-into
/// implicit dependency.
///
/// Scope ids live in the `Selection` params rather than in graph slots:
/// selection membership is dynamic, and §3.5 dirties selections via
/// per-kind indexes at evaluation time, not via structural edges. A scope
/// id that no longer resolves is a per-entity evaluation error, never a
/// crash (§3.4/§6.4).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SelectionScope {
    /// An explicit candidate set.
    Entities(Vec<EntityId>),
    /// All entities in an `Element`'s construction subtree.
    Element(EntityId),
    /// Document-global, filtered by kind — re-evaluates on any change to a
    /// matching kind (the documented price of globality).
    Global { kinds: Vec<EntityKind> },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn predicate_ast_round_trips_serde() {
        let pred = PredicateAst::And(vec![
            PredicateAst::KindIs(EntityKind::Edge),
            PredicateAst::Or(vec![
                PredicateAst::EndpointsOnPlane { z: 3.0, tol: 1e-5 },
                PredicateAst::Not(Box::new(PredicateAst::OwnerIs(EntityId(7)))),
            ]),
            PredicateAst::LengthBetween { min: 0.1, max: 2.5 },
            PredicateAst::WithinBox {
                min: [0.0, 0.0, 0.0],
                max: [10.0, 10.0, 3.0],
            },
        ]);
        let bytes = postcard::to_allocvec(&pred).ok();
        assert!(bytes.is_some());
        let back: Option<PredicateAst> =
            bytes.as_deref().and_then(|b| postcard::from_bytes(b).ok());
        assert_eq!(back.as_ref(), Some(&pred));
    }

    #[test]
    fn scope_round_trips_serde() {
        let scope = SelectionScope::Global {
            kinds: vec![EntityKind::Edge, EntityKind::Face],
        };
        let bytes = postcard::to_allocvec(&scope).ok();
        let back: Option<SelectionScope> =
            bytes.as_deref().and_then(|b| postcard::from_bytes(b).ok());
        assert_eq!(back.as_ref(), Some(&scope));
    }
}
