//! VIM Design C ABI — skeleton.
//!
//! Contract (docs/ARCHITECTURE.md §§8–9): every entry point returns a
//! `VimStatus`, never unwinds across the FFI boundary (`catch_unwind`
//! backstop), and documents are opaque handles from `vim_create` /
//! `vim_destroy`. The header `include/vim_design.h` is generated by
//! cbindgen in build.rs.

use std::os::raw::c_char;
use std::panic::{AssertUnwindSafe, catch_unwind};

use vim_design_lib::Document;

/// Result status returned by every VIM Design C API function. 0 is success.
///
/// Mirrors `vim_design_lib::VimStatus`; keep discriminants in sync.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VimStatus {
    Ok = 0,
    NullArgument = 1,
    InvalidHandle = 2,
    EntityNotFound = 3,
    HasDependents = 4,
    WouldCreateCycle = 5,
    UnsupportedVersion = 6,
    InternalPanic = 7,
}

/// Opaque VIM Design document handle. Create with `vim_create`, release
/// with `vim_destroy`. A handle is NOT thread-safe; synchronize all calls
/// on one handle externally (calls on different handles are safe
/// concurrently).
pub struct VimDesign {
    document: Document,
}

fn ffi_guard(body: impl FnOnce() -> VimStatus) -> VimStatus {
    match catch_unwind(AssertUnwindSafe(body)) {
        Ok(status) => status,
        Err(_) => VimStatus::InternalPanic,
    }
}

/// Create a new, empty VIM Design document.
///
/// On success writes a non-null handle to `out_handle` and returns
/// `VimStatus::Ok`. The handle must be released with `vim_destroy`.
#[unsafe(no_mangle)]
pub extern "C" fn vim_create(out_handle: *mut *mut VimDesign) -> VimStatus {
    ffi_guard(|| {
        if out_handle.is_null() {
            return VimStatus::NullArgument;
        }
        let handle = Box::new(VimDesign {
            document: Document::new(),
        });
        // SAFETY: out_handle was checked non-null; the caller guarantees it
        // points to writable storage for one pointer.
        unsafe {
            *out_handle = Box::into_raw(handle);
        }
        VimStatus::Ok
    })
}

/// Destroy a document previously created with `vim_create`.
///
/// Passing NULL returns `VimStatus::NullArgument`. After this call the
/// handle is invalid and must not be used again.
#[unsafe(no_mangle)]
pub extern "C" fn vim_destroy(handle: *mut VimDesign) -> VimStatus {
    ffi_guard(|| {
        if handle.is_null() {
            return VimStatus::NullArgument;
        }
        // SAFETY: the caller guarantees `handle` came from vim_create and
        // has not already been destroyed.
        let owned = unsafe { Box::from_raw(handle) };
        // Touch the document so the placeholder wiring is exercised.
        let _generation = owned.document.generation();
        drop(owned);
        VimStatus::Ok
    })
}

/// Returns the VIM Design library version as a static NUL-terminated
/// UTF-8 string. Never returns NULL; the pointer is valid for the lifetime
/// of the process and must not be freed.
#[unsafe(no_mangle)]
pub extern "C" fn vim_version() -> *const c_char {
    // Static storage, NUL-terminated at compile time.
    const VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "\0");
    VERSION.as_ptr() as *const c_char
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ptr;

    #[test]
    fn create_destroy_roundtrip() {
        let mut handle: *mut VimDesign = ptr::null_mut();
        assert_eq!(vim_create(&mut handle), VimStatus::Ok);
        assert!(!handle.is_null());
        assert_eq!(vim_destroy(handle), VimStatus::Ok);
    }

    #[test]
    fn null_arguments_are_rejected() {
        assert_eq!(vim_create(ptr::null_mut()), VimStatus::NullArgument);
        assert_eq!(vim_destroy(ptr::null_mut()), VimStatus::NullArgument);
    }

    #[test]
    fn version_is_nul_terminated() {
        let ptr = vim_version();
        assert!(!ptr.is_null());
        // SAFETY: vim_version guarantees a static NUL-terminated string.
        let s = unsafe { std::ffi::CStr::from_ptr(ptr) };
        assert_eq!(s.to_str().ok(), Some(env!("CARGO_PKG_VERSION")));
    }
}
