//! Test plan (f): structural-only geometry commands — chamfers fed by
//! explicit edges and by selections, selections with predicate ASTs that
//! round-trip serde, and section boxes. All deletable and undoable.
//! No geometry is evaluated anywhere here (that is the next milestone).

use vim_design_lib::{
    Command, Document, EntityKind, Params, PredicateAst, SelectionScope, SlotValue,
    VimStatus,
};
use vim_design_test::{assert_save_load_roundtrip, build_chain, one, ok, save};

fn sample_predicate() -> PredicateAst {
    // "Edges whose endpoints lie on the z = 3 m plane, at most 2.5 m long,
    // not generated by entity 42" — structural placeholder semantics only.
    PredicateAst::And(vec![
        PredicateAst::KindIs(EntityKind::Edge),
        PredicateAst::EndpointsOnPlane { z: 3.0, tol: 1e-5 },
        PredicateAst::LengthBetween { min: 0.0, max: 2.5 },
        PredicateAst::Not(Box::new(PredicateAst::OwnerIs(vim_design_lib::EntityId(42)))),
    ])
}

#[test]
fn chamfer_accepts_explicit_edges_and_selections() {
    let mut doc = Document::new();
    let chain = build_chain(&mut doc);

    // A second edge so the multi slot is exercised with several entries.
    let edge2 = one(&mut doc, Command::CreateEdge { curve: chain.line });

    // Selection over the whole document's edges.
    let selection = one(
        &mut doc,
        Command::CreateSelection {
            predicate: sample_predicate(),
            scope: SelectionScope::Global {
                kinds: vec![EntityKind::Edge],
            },
            frozen: false,
        },
    );

    // Explicit edges AND a selection in the same multi slot.
    let chamfer = one(
        &mut doc,
        Command::CreateChamfer {
            distance: 0.02,
            edges: vec![chain.edge, edge2, selection],
        },
    );
    assert_eq!(
        doc.entity(chamfer).map(|r| r.inputs.clone()),
        Some(vec![SlotValue::Many(vec![chain.edge, edge2, selection])])
    );
    assert_eq!(
        doc.dependents(selection),
        Ok(vec![chamfer]),
        "the selection is a real graph dependency of the chamfer"
    );

    // Update: distance and a reduced edge set (multi-slot rewire).
    ok(
        &mut doc,
        Command::UpdateChamfer {
            id: chamfer,
            distance: Some(0.05),
            edges: Some(vec![selection]),
            coalesce: false,
        },
    );
    assert_eq!(
        doc.dependents(chain.edge).map(|d| d.contains(&chamfer)),
        Ok(false),
        "explicit edges unwired"
    );

    // The selection now has a dependent: deleting it must be rejected.
    assert_eq!(
        doc.submit(Command::DeleteSelection { id: selection }).err(),
        Some(VimStatus::HasDependents)
    );

    // Deletable and undoable.
    ok(&mut doc, Command::DeleteChamfer { id: chamfer });
    ok(&mut doc, Command::DeleteSelection { id: selection });
    doc.undo().expect("undo delete selection");
    doc.undo().expect("undo delete chamfer");
    assert_eq!(
        doc.entity(chamfer).map(|r| r.kind()),
        Some(EntityKind::Chamfer),
        "chamfer restored with the same id"
    );

    assert_save_load_roundtrip(&doc);
}

#[test]
fn selection_predicate_round_trips_through_serde_and_save() {
    let mut doc = Document::new();
    let chain = build_chain(&mut doc);
    let predicate = sample_predicate();

    // Direct serde round-trip of the AST (postcard, the wire format).
    let bytes = postcard::to_allocvec(&predicate).expect("serialize predicate");
    let back: PredicateAst = postcard::from_bytes(&bytes).expect("deserialize predicate");
    assert_eq!(back, predicate);

    // And through a Selection entity + full document save/load.
    let scoped = one(
        &mut doc,
        Command::CreateSelection {
            predicate: predicate.clone(),
            scope: SelectionScope::Entities(vec![chain.edge, chain.face]),
            frozen: true,
        },
    );
    let saved = save(&doc);
    let reloaded = Document::load(&saved).expect("load");
    let params = reloaded.entity(scoped).map(|r| r.params.clone());
    assert_eq!(
        params,
        Some(Params::Selection {
            predicate,
            scope: SelectionScope::Entities(vec![chain.edge, chain.face]),
            frozen: true,
        })
    );

    // Scope ids are existence-checked at creation time.
    assert_eq!(
        doc.submit(Command::CreateSelection {
            predicate: PredicateAst::KindIs(EntityKind::Edge),
            scope: SelectionScope::Element(chain.face), // not an Element
            frozen: false,
        })
        .err(),
        Some(VimStatus::WrongEntityKind)
    );

    assert_save_load_roundtrip(&doc);
}

#[test]
fn section_box_lifecycle() {
    let mut doc = Document::new();
    build_chain(&mut doc);

    let bytes_before = save(&doc);
    let boxed = one(
        &mut doc,
        Command::CreateSectionBox {
            min: [-10.0, -10.0, 0.0],
            max: [10.0, 10.0, 4.0],
        },
    );
    // Section boxes take part in no graph edges (docs/ARCHITECTURE.md §14).
    assert_eq!(doc.dependents(boxed), Ok(vec![]));

    ok(
        &mut doc,
        Command::UpdateSectionBox {
            id: boxed,
            min: None,
            max: Some([10.0, 10.0, 2.0]),
            coalesce: false,
        },
    );
    assert_eq!(
        doc.entity(boxed).map(|r| r.params.clone()),
        Some(Params::SectionBox {
            min: [-10.0, -10.0, 0.0],
            max: [10.0, 10.0, 2.0],
        })
    );

    ok(&mut doc, Command::DeleteSectionBox { id: boxed });
    assert!(doc.entity(boxed).is_none());

    // Fully undoable back to the pre-scenario bytes.
    doc.undo().expect("undo delete");
    doc.undo().expect("undo update");
    doc.undo().expect("undo create");
    assert_eq!(save(&doc), bytes_before);

    assert_save_load_roundtrip(&doc);
}
